#!/bin/bash

function createBank() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/bank.creditrisk.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/bank.creditrisk.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-bank --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bank.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bank.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bank.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bank.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy bank's CA cert to bank's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/bank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/tlscacerts/ca.crt"

  # Copy bank's CA cert to bank's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/bank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/tlsca/tlsca.bank.creditrisk.com-cert.pem"

  # Copy bank's CA cert to bank's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/ca"
  cp "${PWD}/organizations/fabric-ca/bank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/ca/ca.bank.creditrisk.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-bank --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-bank --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-bank --id.name bankadmin --id.secret bankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-bank -M "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-bank -M "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls" --enrollment.profile tls --csr.hosts peer0.bank.creditrisk.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/peers/peer0.bank.creditrisk.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-bank -M "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/users/User1@bank.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/users/User1@bank.creditrisk.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://bankadmin:bankadminpw@localhost:7054 --caname ca-bank -M "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/users/Admin@bank.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bank.creditrisk.com/users/Admin@bank.creditrisk.com/msp/config.yaml"
}

function createPlatform() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/platform.creditrisk.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/platform.creditrisk.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-platform --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-platform.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-platform.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-platform.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-platform.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy platform's CA cert to platform's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/tlscacerts/ca.crt"

  # Copy platform's CA cert to platform's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/tlsca/tlsca.platform.creditrisk.com-cert.pem"

  # Copy platform's CA cert to platform's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/ca"
  cp "${PWD}/organizations/fabric-ca/platform/ca-cert.pem" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/ca/ca.platform.creditrisk.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-platform --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-platform --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-platform --id.name platformadmin --id.secret platformadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls" --enrollment.profile tls --csr.hosts peer0.platform.creditrisk.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/peers/peer0.platform.creditrisk.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/users/User1@platform.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/users/User1@platform.creditrisk.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://platformadmin:platformadminpw@localhost:8054 --caname ca-platform -M "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/users/Admin@platform.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/platform/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/platform.creditrisk.com/users/Admin@platform.creditrisk.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/creditrisk.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/creditrisk.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/creditrisk.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/creditrisk.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/creditrisk.com/msp/tlscacerts/tlsca.creditrisk.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/creditrisk.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/creditrisk.com/tlsca/tlsca.creditrisk.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls" --enrollment.profile tls --csr.hosts orderer.creditrisk.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/creditrisk.com/orderers/orderer.creditrisk.com/msp/tlscacerts/tlsca.creditrisk.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/creditrisk.com/users/Admin@creditrisk.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/creditrisk.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/creditrisk.com/users/Admin@creditrisk.com/msp/config.yaml"
}
